#!/bin/bash
#SBATCH --nodes=1 
#SBATCH --mem=20GB 
#SBATCH --time=2:00:00 

#Peter Laurin
#
#Script to generate 'plinkable' file for snp set in linkage equilibrium 
#and to prune snps based on 0.8 r^2, 0.03 maf 
#
#run on NYU Greene, or some hpc with SLURM-managed tasks 
#one node, 20 gb memory, 2 hr run time 
#
# TOUA_pass.vcf generated by vcf_subset.s


module load bcftools/intel/1.11 plink/1.90b6.21

#make file 'plinkable'
bgzip TOUA_pass.vcf 
bcftools index TOUA_pass.vcf.bgz
for i in 1 2 3 4 5 M C; do echo AtChr$i $i >> new_chroms.txt; done;
bcftools annotate --rename-chrs new_chroms.txt -o TOUA_5c_pass.vcf TOUA_pass.vcf.bgz 

#prune marker set to 0.8 r^2, 0.03 maf
plink --allow-extra-chr --chr 1-5 --double-id --indep-pairwise 50 10 0.8 --maf 0.03 --out TOUA_03_8r --set-missing-var-ids @:# --vcf ../TOUA_5c_pass.vcf
plink --allow-extra-chr --double-id --extract TOUA_03_8r.prune.in --make-bed --out TOUA_03_8r_pca --pca --set-missing-var-ids @:# --vcf ../TOUA_5c_pass.vcf

#rewrite marker set as vcf to extract snps for window
plink --bfile TOUA_03_8r_pca --out TOUA_LD_fil_new --recode vcf 

#run admixture batch, from K=1-15
sbatch TOUA_batch_admixture.s 

sleep 60m

#make folder to generate plots 
mkdir TOUA
cd TOUA
for i in {1..15}; do cp admixture$i/*.P ./

#find snps around window
cp ../TOUA_pop_strat_windows.sh ./
bash TOUA_pop_strat_windows.sh

#generate positions for P files 
tail -n +11 TOUA_LD_fil_new.vcf | cut -f 3 > SNP_IDs.txt

cd ..
